spring:
  application:
    name: ${SPRING_APP_NAME:eazybankbackend}
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{yyyy/MM/dd-HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:debug}
