server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: ${SPRING_APP_NAME:eazybankbackend}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:192.168.1.205}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USER:yascode}
    password: ${DATABASE_PASSWORD:yascode}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{yyyy/MM/dd-HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:debug}

---

server:
  port: ${SERVER_PORT:8443}
  ssl:
    key-store: ${KEY_STORE:classpath:keystores/keystore.p12}
    key-store-password: ${KEY_PASSWORD:yascode}
    key-store-type: ${KEY_STORE_TYPE:PKCS12}
    key-alias: ${KEY_ALIAS:yascode}
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:192.168.1.205}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USER:yascode}
    password: ${DATABASE_PASSWORD:yascode}
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{yyyy/MM/dd-HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:error}